Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -59,7 +59,7 @@ env:
   msys_prefix: 'mingw-w64'
   toolchain_arch: 'clang-aarch64'
   package_prefix: 'mingw-w64-clang-aarch64'
-  repo: "https://github.com/FFmpeg/FFmpeg"
+  source_repo: "https://github.com/FFmpeg/FFmpeg"
 
 jobs:
   setup-defaults:
@@ -101,11 +101,19 @@ jobs:
         run: |
           ls -F
           echo $GITHUB_WORKSPACE
-          echo "${GITHUB_WORKSPACE}/source"
+          echo "${GITHUB_WORKSPACE}\source"
           # git clone https://github.com/username/repository.git $source_path
           echo "Repository cloned to: $source_path"
           echo $repo
-          # git clone --branch <tag_name> ${env.repo}
+          # git clone --branch $inputs_github_tag $source_repo "${GITHUB_WORKSPACE}\source"
+          cd source
+          if test -f "release"; then
+            version=$(<release)
+          else
+            echo "release version not found"
+            exit 1
+          fi
+          echo $version
   # msys2:
   #   name: '⚒️ Setup MSYS2 Environment'
   #   needs: ['setup-defaults']
