Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -125,15 +125,18 @@ jobs:
             diffutils:p
             jq:p
             github-cli:p
-    - name: '🛒 Checkout'
-      uses: actions/checkout@v5
-    - name: "📦 Install support packages - Generic Build"
-      working-directory: ./config
+    - name: 'test'
       run: |
-        echo "Install support packages - Generic Build"
-        packages=$(jq -r --arg prefix "$package_prefix" '.options.base.extras | map(.package) | map($prefix + "-" + .) | join(" ")' options.json)
-        echo $packages
-        pacman -S --noconfirm --overwrite '*' $packages
+        echo $env:MSYS2_LOCATION"
+    # - name: '🛒 Checkout'
+    #   uses: actions/checkout@v5
+    # - name: "📦 Install support packages - Generic Build"
+    #   working-directory: ./config
+    #   run: |
+    #     echo "Install support packages - Generic Build"
+    #     packages=$(jq -r --arg prefix "$package_prefix" '.options.base.extras | map(.package) | map($prefix + "-" + .) | join(" ")' options.json)
+    #     echo $packages
+    #     pacman -S --noconfirm --overwrite '*' $packages
     # - name: "📦 Install base level packages - Essentials Build"
     #   working-directory: ./config
     #   run: |
@@ -171,37 +174,39 @@ jobs:
     #     echo "Install Custom Packages from External Repo"
     #     cd packages
     #     pacman -U --overwrite '*' --noconfirm *.pkg.tar.zst
-    # - name: "⬇️ Download External Utlities"
+    # # - name: "⬇️ Download External Utlities"
+    # #   run: |
+    # #     mkdir utilities
+    # #     gh release download "rcedit" -D "./utilities" -R tordona/win-arm64-binaries
+    # #     cd utilities
+    # #     ls -la
+    # - name: "🌪️ Clone FFmpeg source repository"
     #   run: |
-    #     mkdir utilities
-    #     gh release download "rcedit" -D "./utilities" -R tordona/win-arm64-binaries
-    #     cd utilities
-    #     ls -la
-    - name: "🌪️ Clone FFmpeg source repository"
-      run: |
-        mkdir source
-        git clone --branch $inputs_github_tag $source_repo ./source
-        cd source
-        if test -f "RELEASE"; then
-          version=$(<RELEASE)
-          echo "source_version=$version" >> $GITHUB_ENV
-        else
-          echo "release version not found"
-          exit 1
-        fi
-    - name: "🔨 Test: Configure FFmpeg"
-      continue-on-error: true
-      run: |
-        echo "Test tooling and library availability"
-        cd source
-        extra="--extra-libs='-static -lpthread -lm -liconv'"
-        arch="--arch=${toolchain_arch##clang\-}"
-        generic_options=$(jq -r '.options.generic | map("--\(.status)-\(.option)") | join(" ")' ../config/options.json)
-        command="./configure $extra $arch $generic_options"
-        echo $command
-        eval $command
-    - name: "🔨 Test: Configure FFmpeg"
-      run: |
-        echo "Test tooling and library availability"
-        cd source/ffbuild
-        cat config.log
+    #     mkdir source
+    #     git clone --branch $inputs_github_tag $source_repo ./source
+    #     cd source
+    #     if test -f "RELEASE"; then
+    #       version=$(<RELEASE)
+    #       echo "source_version=$version" >> $GITHUB_ENV
+    #     else
+    #       echo "release version not found"
+    #       exit 1
+    #     fi
+    # - name: "🔨 Test: Configure FFmpeg"
+    #   continue-on-error: true
+    #   run: |
+    #     echo "Test tooling and library availability"
+    #     cd source
+    #     echo $env:MSYS2_LOCATION"
+    #     # /configure --extra-libs='-static -lpthread -lm -liconv' --arch=aarch64 --enable-gpl --enable-version3 --enable-pic --enable-static --disable-shared --disable-debug --disable-w32threads --enable-pthreads --disable-autodetect --enable-iconv --enable-libxml2 --enable-bzlib --enable-lzma --enable-zlib --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-avisynth --enable-libaom  --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libspeex --enable-libsrt --enable-libtheora --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-mediafoundation --enable-sdl2 --enable-frei0r --enable-ladspa --enable-lcms2 --enable-libbs2b --enable-libcdio --enable-libdav1d --enable-libdvdnav --enable-libdvdread --enable-liblc3 --enable-libmysofa --enable-librav1e --enable-librist --enable-libshine --enable-libsnappy --enable-libsvtav1 --enable-libtwolame --enable-libxevd --enable-libxeve --enable-libzvbi --enable-liboapv --enable-libvvenc --enable-pic --disable-manpages --disable-podpages --disable-txtpages --extra-cflags=-I/d/msys64-dev/clangarm64/include --extra-ldflags='-Wl,--allow-multiple-definition'
+    #     extra="--extra-libs='-static -lpthread -lm -liconv'"
+    #     arch="--arch=${toolchain_arch##clang\-}"
+    #     generic_options=$(jq -r '.options.generic | map("--\(.status)-\(.option)") | join(" ")' ../config/options.json)
+    #     command="./configure $extra $arch $generic_options"
+    #     echo $command
+    #     eval $command
+    # - name: "🔨 Test: Configure FFmpeg"
+    #   run: |
+    #     echo "Test tooling and library availability"
+    #     cd source/ffbuild
+    #     cat config.log
