Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -64,220 +64,200 @@ env:
   source_version: "0"
 
 jobs:
-  setup-defaults:
-    name: '🌐 Setup Environment Variables'
-    runs-on: ubuntu-latest
-    outputs:
-      env: ${{ env }}
-    steps:
-      - name: '🛒 Checkout'
-        uses: actions/checkout@v5
-      - name: '🗺️ Map Workflow Inputs to Environment Variables'
-        shell: bash
-        run: |
-          github_tag="${{ inputs.github_tag || 'n8.0.1' }}"
-          echo "inputs_github_tag=${github_tag}" >> $GITHUB_ENV
-
-          build_type="${{ inputs.build_type || 'essentials' }}"
-          echo "inputs_build_type=${build_type}" >> $GITHUB_ENV
-
-          link_type="${{ inputs.link_type || 'shared' }}"
-          echo "inputs_link_type=${link_type} " >> $GITHUB_ENV
-
-          msystem="${{ inputs.msystem || 'CLANGARM64' }}"
-          echo "inputs_msystem=${msystem}" >> $GITHUB_ENV
-
-          environment="${{ inputs.environment || 'CLANGARM64' }}"
-          echo "inputs_environment=${environment}" >> $GITHUB_ENV
-      - name: '🗺️ Map FFmpeg Version'
-        shell: bash
-        run: |
-          if [[ ${{ env.inputs_github_tag }} =~ ([0-9]+) ]]; then
-              major_version="${BASH_REMATCH[1]}"
-              echo "ffmpeg_version=${major_version}" >> $GITHUB_ENV
-          fi
-      - name: '🗺️ Map Toolchain Architecture Name'
-        shell: bash
-        run: |
-          if [[ ${{ env.inputs_msystem }} == "CLANGARM64" ]]; then
-              echo "arch=aarch64" >> $GITHUB_ENV
-              echo "toolchain_arch=clang-aarch64" >> $GITHUB_ENV
-              echo "package_prefix=${{ env.msys_prefix }}-clang-aarch64" >> $GITHUB_ENV
-          elif [[ ${{ env.inputs_msystem }} == "CLANG64" ]]; then
-              echo "arch=x86_64" >> $GITHUB_ENV
-              echo "toolchain_arch=clang-x86_64" >> $GITHUB_ENV
-              echo "package_prefix=${{ env.msys_prefix }}-clang-x86_64" >> $GITHUB_ENV
-          fi
-      - name: '🗺️ Verify Environment Variables'
-        shell: bash
-        run: |
-          echo "env=${{ env }}-clang-x86_64" >> $GITHUB_ENV
-  setup-ffmpeg-options:
-    name: '🎞️ Setup FFmpeg Configuration'
-    runs-on: ubuntu-latest
-    outputs:
-      ffmpeg-config: ${{ env.build_config }}
+  # setup-ffmpeg-options:
+  #   name: '🎞️ Setup FFmpeg Configuration'
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     ffmpeg-config: ${{ env.build_config }}
+  #   env:
+  #     build_config: "./configure "
+  #   steps:
+  #   - name: '🛒 Checkout'
+  #     uses: actions/checkout@v5
+  #   - name: '🗺️ Setup FFmpeg Baseline Configuration'
+  #     working-directory: ./config
+  #     run: |
+  #       base_config=$(jq -r '.config' options.json)
+  #       echo "build_config=${base_config}" >> $GITHUB_ENV
+  #   - name: '🏛️ Set Target Architecture'
+  #     run: |
+  #       echo "Set Explict Architecture Option Value"
+  #       if [[ ${{ env.inputs_msystem }} == "CLANGARM64" ]]; then
+  #         temp_config=" --arch=aarch64"
+  #       elif [[ ${{ env.inputs_msystem }} == "CLANG64" ]]; then
+  #         temp_config="--arch=x86_64"
+  #       fi
+  #       echo "build_config=$build_config$temp_config" >> $GITHUB_ENV
+  #   - name: '🔗 Set Link Type'
+  #     run: |
+  #       if [[ ${{ env.inputs_link_type }} == "shared" ]]; then
+  #         temp_config=" --enable-shared --disable-static"
+  #       else
+  #         temp_config=" --disable-shared --enable-static"
+  #       fi
+  #       echo "build_config=$build_config$temp_config" >> $GITHUB_ENV
+  #   - name: '🏴 Set Compile LDFLAGS'
+  #     working-directory: ./config
+  #     run: |
+  #       if [[ ${{ env.inputs_github_tag }} =~ ([0-9]+) ]]; then
+  #         major_version="${BASH_REMATCH[1]}"
+  #         options=$(jq -r --arg version $major_version '[.options.standard[], .options.essentials[], .options.full[] | .[] | select(.version <= $version) | .option] | join(" ")' options.json)
+  #         echo $options
+  #         if [[ "$options" == *"librav1e"* && "$options" == *"libplacebo"* ]]; then
+  #           temp_config=" --extra-ldflags='-Wl,--allow-multiple-definition"
+  #           echo "build_config=$build_config$temp_config" >> $GITHUB_ENV
+  #         fi
+  #       fi
+  #   - name: '🐬 Echo Configuration'
+  #     id: 'ffmpeg-config'
+  #     run: |
+  #       echo $build_config
+  # setup-test:
+  #   name: '🌐 Setup Environment Variabless'
+  #   runs-on: ubuntu-latest
+  #   needs: ['setup-defaults', 'setup-ffmpeg-options']
+  #   steps:
+  #     - name: test
+  #       run: |
+  #         echo "${{ needs.setup-defaults.outputs.env }}"
+  #         echo "${{ needs.setup-ffmpeg-options.outputs.ffmpeg-config }}"
+  msys2:
+    name: '💻 MSYS2 Environment'
+    runs-on: windows-11-arm
     env:
-      build_config: "./configure "
+      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    defaults:
+      run:
+        shell: msys2 {0}
     steps:
     - name: '🛒 Checkout'
       uses: actions/checkout@v5
-    - name: '🗺️ Setup FFmpeg Baseline Configuration'
-      working-directory: ./config
+    - name: '🗺️ Map Workflow Inputs to Environment Variables'
+      shell: bash
       run: |
-        base_config=$(jq -r '.config' options.json)
-        echo "build_config=${base_config}" >> $GITHUB_ENV
-    - name: '🏛️ Set Target Architecture'
+        github_tag="${{ inputs.github_tag || 'n8.0.1' }}"
+        echo "inputs_github_tag=${github_tag}" >> $GITHUB_ENV
+
+        build_type="${{ inputs.build_type || 'essentials' }}"
+        echo "inputs_build_type=${build_type}" >> $GITHUB_ENV
+
+        link_type="${{ inputs.link_type || 'shared' }}"
+        echo "inputs_link_type=${link_type} " >> $GITHUB_ENV
+
+        msystem="${{ inputs.msystem || 'CLANGARM64' }}"
+        echo "inputs_msystem=${msystem}" >> $GITHUB_ENV
+
+        environment="${{ inputs.environment || 'CLANGARM64' }}"
+        echo "inputs_environment=${environment}" >> $GITHUB_ENV
+    - name: '🗺️ Map Toolchain Architecture Name'
+      shell: bash
       run: |
-        echo "Set Explict Architecture Option Value"
         if [[ ${{ env.inputs_msystem }} == "CLANGARM64" ]]; then
-          temp_config=" --arch=aarch64"
+            echo "arch=aarch64" >> $GITHUB_ENV
+            echo "toolchain_arch=clang-aarch64" >> $GITHUB_ENV
+            echo "package_prefix=${{ env.msys_prefix }}-clang-aarch64" >> $GITHUB_ENV
         elif [[ ${{ env.inputs_msystem }} == "CLANG64" ]]; then
-          temp_config="--arch=x86_64"
+            echo "arch=x86_64" >> $GITHUB_ENV
+            echo "toolchain_arch=clang-x86_64" >> $GITHUB_ENV
+            echo "package_prefix=${{ env.msys_prefix }}-clang-x86_64" >> $GITHUB_ENV
         fi
-        echo "build_config=$build_config$temp_config" >> $GITHUB_ENV
-    - name: '🔗 Set Link Type'
+    - name: '🔧 Setup MSYS2'
+      id: msys2-setup
+      uses: msys2/setup-msys2@v2
+      with:
+        msystem: ${{ env.inputs_msystem }}
+        update: true
+        cache: true
+        release: true
+        install:
+            gcc
+            git
+            make
+        pacboy:
+            toolchain:p
+            gcc-compat:p
+            diffutils:p
+            libssh2:p
+            jq:p
+            github-cli:p
+    - name: 'Verify MSYS2 Install'
       run: |
-        if [[ ${{ env.inputs_link_type }} == "shared" ]]; then
-          temp_config=" --enable-shared --disable-static"
+        echo "MSYS2 is installed at: ${{ steps.msys2-setup.outputs.msys2-location }}"
+    - name: "🌪️ Clone FFmpeg source repository"
+      run: |
+        mkdir source
+        git -c advice.detachedHead=false clone --branch $inputs_github_tag $source_repo ./source
+        cd source
+        if test -f "RELEASE"; then
+          version=$(<RELEASE)
+          echo "source_version=$version" >> $GITHUB_ENV
         else
-          temp_config=" --disable-shared --enable-static"
+          echo "Release Version Not Found"
+          exit 1
         fi
-        echo "build_config=$build_config$temp_config" >> $GITHUB_ENV
-    - name: '🏴 Set Compile LDFLAGS'
+    - name: "📦 Install packages - Essentials Build"
       working-directory: ./config
       run: |
-        if [[ ${{ env.inputs_github_tag }} =~ ([0-9]+) ]]; then
-          major_version="${BASH_REMATCH[1]}"
-          options=$(jq -r --arg version $major_version '[.options.standard[], .options.essentials[], .options.full[] | .[] | select(.version <= $version) | .option] | join(" ")' options.json)
-          echo $options
-          if [[ "$options" == *"librav1e"* && "$options" == *"libplacebo"* ]]; then
-            temp_config=" --extra-ldflags='-Wl,--allow-multiple-definition"
-            echo "build_config=$build_config$temp_config" >> $GITHUB_ENV
-          fi
-        fi
-    - name: '🐬 Echo Configuration'
-      id: 'ffmpeg-config'
+        echo "Install required library packages - Essentials Build
+        packages=$(jq -r --arg version "$source_version" --arg prefix "$package_prefix"  '[.options.standard[], .options.essentials[] | .[] | select(.version <= $version) | $prefix + "-" + .package] | join(" ")' options.json)
+        echo $packages
+        pacman -S --noconfirm --overwrite '*' $packages
+    - name: "📦 Install base level packages - Full Build"
+      if: ${{ env.inputs_build_type == 'full' }}
+      working-directory: ./config
       run: |
-        echo $build_config
-  setup-test:
-    name: '🌐 Setup Environment Variabless'
-    runs-on: ubuntu-latest
-    needs: ['setup-defaults', 'setup-ffmpeg-options']
-    steps:
-      - name: test
-        run: |
-          echo "${{ needs.setup-defaults.outputs.env }}"
-          echo "${{ needs.setup-ffmpeg-options.outputs.ffmpeg-config }}"
-  # msys2:
-  #   name: '💻 MSYS2 Environment'
-  #   runs-on: windows-11-arm
-  #   needs: ['setup-defaults']
-  #   env:
-  #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  #   defaults:
-  #     run:
-  #       shell: msys2 {0}
-  #   steps:
-  #   - name: '🔧 Setup MSYS2'
-  #     id: msys2-setup
-  #     uses: msys2/setup-msys2@v2
-  #     with:
-  #       msystem: ${{ env.inputs_msystem }}
-  #       update: true
-  #       cache: true
-  #       release: true
-  #       install:
-  #           gcc
-  #           git
-  #           make
-  #       pacboy:
-  #           toolchain:p
-  #           gcc-compat:p
-  #           diffutils:p
-  #           libssh2:p
-  #           jq:p
-  #           github-cli:p
-  #   - name: 'Verify MSYS2 Install'
-  #     run: |
-  #       echo "MSYS2 is installed at: ${{ steps.msys2-setup.outputs.msys2-location }}"
-  #   - name: '🛒 Checkout'
-  #     uses: actions/checkout@v5
-  #   - name: "🌪️ Clone FFmpeg source repository"
-  #     run: |
-  #       mkdir source
-  #       git -c advice.detachedHead=false clone --branch $inputs_github_tag $source_repo ./source
-  #       cd source
-  #       if test -f "RELEASE"; then
-  #         version=$(<RELEASE)
-  #         echo "source_version=$version" >> $GITHUB_ENV
-  #       else
-  #         echo "Release Version Not Found"
-  #         exit 1
-  #       fi
-  #   - name: "📦 Install packages - Essentials Build"
-  #     working-directory: ./config
-  #     run: |
-  #       echo "Install required library packages - Essentials Build
-  #       packages=$(jq -r --arg version "$source_version" --arg prefix "$package_prefix"  '[.options.standard[], .options.essentials[] | .[] | select(.version <= $version) | $prefix + "-" + .package] | join(" ")' options.json)
-  #       echo $packages
-  #       pacman -S --noconfirm --overwrite '*' $packages
-  #   - name: "📦 Install base level packages - Full Build"
-  #     if: ${{ env.inputs_build_type == 'full' }}
-  #     working-directory: ./config
-  #     run: |
-  #       echo "Install required library packages - Full Build
-  #       packages=$(jq -r --arg version "$source_version" --arg prefix "$package_prefix"  '[.options.full[] | .[] | select(.version <= $version) | $prefix + "-" + .package] | join(" ")' options.json)
-  #       echo $packages
-  #       pacman -S --noconfirm --overwrite '*' $packages
-  #   - name: "⬇️ Download External Packages"
-  #     run: |
-  #      mkdir packages
-  #      gh release download "${toolchain_arch}" --pattern "*.zst" -D "./packages" -R tordona/mingw-packages
-  #   - name: "➡️ Install External Packages"
-  #     run: |
-  #       echo "Install Custom Packages from External Repo"
-  #       cd packages
-  #       pacman -U --overwrite '*' --noconfirm *.pkg.tar.zst
-  #   # - name: "⬇️ Download External Utlities"
-  #   #   run: |
-  #   #     mkdir utilities
-  #   #     gh release download "rcedit" -D "./utilities" -R tordona/win-arm64-binaries
-  #   #     cd utilities
-  #   #     ls -la
-  #   - uses: hmarr/debug-action@v3
-  #   - name: "🔨 Test: Configure FFmpeg"
-  #     continue-on-error: true
-  #     run: |
-  #       echo "Test tooling and library availability"
-  #       echo "MSYS2 is installed at: ${{ steps.msys2-setup.outputs.msys2-location }}"
-  #       cd source
-  #       # echo "$env:MSYS2_LOCATION"
-  #       # extra="--extra-libs='-static -lpthread -lm -liconv'"
-  #       # arch="--arch=${toolchain_arch##clang\-}"
-  #       # generic_options=$(jq -r '.options.generic | map("--\(.status)-\(.option)") | join(" ")' ../config/options.json)
-  #       # essential_base_options=$(jq -r '.options.essentials.base | map("--enable-\(.option)") | join(" ")' ../config/options.json)
-  #       # essential_external_options=$(jq -r '.options.essentials.external | map("--enable-\(.option)") | join(" ")' ../config/options.json)
-  #       # essential_dependent_options=$(jq -r '.options.essentials.dependent | map("--enable-\(.option)") | join(" ")' ../config/options.json)
-  #       # command="./configure $extra $arch --enable-shared --disable-static $generic_options $essential_base_options $essential_external_options $essential_dependent_options"
-  #       echo $command
-  #       eval $command
-  #   - name: "🔨 Test: Configure FFmpeg"
-  #     run: |
-  #       echo "Test tooling and library availability"
-  #       cd source
-  #       cd ffbuild
-  #       cat config.log
-  #   # - name: '🖥️ Get number of CPU cores'
-  #   #   uses: SimenB/github-actions-cpu-cores@v2
-  #   #   id: cpu-cores
-  #   # - name: "🔨 Test: Configure FFmpeg"
-  #   #   run: |
-  #   #     echo "Test tooling and library availability"
-  #   #     cd source
-  #   #     make -j${{ steps.cpu-cores.outputs.count }}
-  #   # - name: "🔨 Test: Configure FFmpeg"
-  #   #   run: |
-  #   #     echo "Test tooling and library availability"
-  #   #     cd source/ffbuild
-  #   #     cat config.log
+        echo "Install required library packages - Full Build
+        packages=$(jq -r --arg version "$source_version" --arg prefix "$package_prefix"  '[.options.full[] | .[] | select(.version <= $version) | $prefix + "-" + .package] | join(" ")' options.json)
+        echo $packages
+        pacman -S --noconfirm --overwrite '*' $packages
+    - name: "⬇️ Download External Packages"
+      run: |
+       mkdir packages
+       gh release download "${toolchain_arch}" --pattern "*.zst" -D "./packages" -R tordona/mingw-packages
+    - name: "➡️ Install External Packages"
+      run: |
+        echo "Install Custom Packages from External Repo"
+        cd packages
+        pacman -U --overwrite '*' --noconfirm *.pkg.tar.zst
+    # - name: "⬇️ Download External Utlities"
+    #   run: |
+    #     mkdir utilities
+    #     gh release download "rcedit" -D "./utilities" -R tordona/win-arm64-binaries
+    #     cd utilities
+    #     ls -la
+    - uses: hmarr/debug-action@v3
+    - name: "🔨 Test: Configure FFmpeg"
+      continue-on-error: true
+      run: |
+        echo "Test tooling and library availability"
+        echo "MSYS2 is installed at: ${{ steps.msys2-setup.outputs.msys2-location }}"
+        cd source
+        # echo "$env:MSYS2_LOCATION"
+        # extra="--extra-libs='-static -lpthread -lm -liconv'"
+        # arch="--arch=${toolchain_arch##clang\-}"
+        # generic_options=$(jq -r '.options.generic | map("--\(.status)-\(.option)") | join(" ")' ../config/options.json)
+        # essential_base_options=$(jq -r '.options.essentials.base | map("--enable-\(.option)") | join(" ")' ../config/options.json)
+        # essential_external_options=$(jq -r '.options.essentials.external | map("--enable-\(.option)") | join(" ")' ../config/options.json)
+        # essential_dependent_options=$(jq -r '.options.essentials.dependent | map("--enable-\(.option)") | join(" ")' ../config/options.json)
+        # command="./configure $extra $arch --enable-shared --disable-static $generic_options $essential_base_options $essential_external_options $essential_dependent_options"
+        echo $command
+        eval $command
+    - name: "🔨 Test: Configure FFmpeg"
+      run: |
+        echo "Test tooling and library availability"
+        cd source
+        cd ffbuild
+        cat config.log
+    # - name: '🖥️ Get number of CPU cores'
+    #   uses: SimenB/github-actions-cpu-cores@v2
+    #   id: cpu-cores
+    # - name: "🔨 Test: Configure FFmpeg"
+    #   run: |
+    #     echo "Test tooling and library availability"
+    #     cd source
+    #     make -j${{ steps.cpu-cores.outputs.count }}
+    # - name: "🔨 Test: Configure FFmpeg"
+    #   run: |
+    #     echo "Test tooling and library availability"
+    #     cd source/ffbuild
+    #     cat config.log
